### ISSUE TITLE
labelled vectors

### ISSUE THREAD

**Issue by andresimi** [ropensci/skimr#296]
Thank you very much for the package.

It would be very nice if skimr worked with labelled vectors (from tidyverse labelled package) and transformed them to factors (to_factor) and included them in the factors session in the output.

Now, it transforms them in character vectors...

**Comment by elinw** [comment]
Can you give me a sample data set? One thing is that you can use skim_with for any class and if you want to use the factor list of statistics you can do that. Unfortunately we can't support every possible data type out of the box but we did make it easy to add a new data type.

**Comment by elinw** [comment]
Okay the documentation is a bit misleading on this, and you have to use an internal function that you shouldn't. 
```
s1 <- labelled(c('M', 'M', 'F'), c(Male = 'M', Female = 'F'))
s1
skim_with(labelled = skimr:::get_funs("factor"))
skim(s1)
```

**Comment by michaelquinn32** [comment]
I think `get_skimmers` should also work in this situation. But there's a small bug where single skimmers aren't being added correctly. We should leave this open until we get around to fixing it.

```
s1 <- labelled(c('M', 'M', 'F'), c(Male = 'M', Female = 'F'))
skim_with(labelled = get_skimmers()$factor)
skim(s1)
```

Sorry about that. I hope this helps.

**Comment by elinw** [comment]
Should we move that to a separate issue since it is no about labelled variables in particular?

**Comment by elinw** [comment]
Are you saying that we should be able to use `get_skimmers("factor")`?  The inline documentation is definitely incorrect in saying you can use `funs$factor`.

**Comment by rubenarslan** [comment]
I think it'd be a nicer default, if skimr skimmed numeric labelled variables as numeric. Is there a way to make the skimmer conditional on such aspects of the variable?

**Comment by elinw** [comment]
You can do it however you want. As long as the functions work.  You can completely replace the functions also. Just change factor to numeric.  The whole idea is that skimr is designed to let you do what you want.

**Comment by rubenarslan** [comment]
Sorry, I don't get it. Maybe an example helps.

``` r
library(labelled)
s1 <- dplyr::data_frame(fac = labelled(c("M", "M", "F"), c(Male = "M", Female = "F")), 
  num = labelled(c(1, 2, 10), c(low = 1, high = 10)))

library(skimr)
skim_with(labelled = get_skimmers()$factor)
#> Adding type: labelled
skim(s1)
#> Skim summary statistics
#>  n obs: 3 
#>  n variables: 2 
#> 
#> Variable type: labelled 
#>  variable missing complete n n_unique               top_counts ordered
#>       fac       0        3 3        2        M: 2, F: 1, NA: 0   FALSE
#>       num       0        3 3        3 1: 1, 2: 1, 10: 1, NA: 0   FALSE
```

If I use numeric above, I get an error. I can't make it conditional on the underlying (unlabelled) data type, right?

I want approximately this output, so maybe I'll have to pre-process the dataset.

```r
skim(s1 %>% haven::zap_labels())
#> Skim summary statistics
#>  n obs: 3 
#>  n variables: 2 
#> 
#> Variable type: character 
#>  variable missing complete n min max empty n_unique
#>       fac       0        3 3   1   1     0        2
#> 
#> Variable type: numeric 
#>  variable missing complete n mean   sd p0 p25 p50 p75 p100     hist
#>       num       0        3 3 4.33 4.93  1 1.5   2   6   10 ââââââââ
```

Generally I think support for labels, including variable labels (as an additional column) would be cool, as it seems within the scope of what skimr is designed to do, but I might be wrong about this :-)

**Comment by elinw** [comment]
You may notice in our README file this statement

> We welcome issue reports and pull requests, including potentially adding support for commonly used variable classes. However, in general, we encourage users to take advantage of skimr's flexibility to add their own customized classes. 

So the point is that you can write support for any class you want. Since the labelled situation is very complex and needs guessing,    you should follow  the instructions in the vignette _Supporting additional objects_ and create a `skim.labelled()` method.  In that method you should come up with a way to guess the type or use the `zap_labels` function to guess the type.  You could do other things as well, such as create a rule about when to treat strings as characters versus factors.  So then maybe you would as part of this change labelled to labelled_numeric and labelled_factor if you have  any special functions that you want to add or change them to one of the supported names. I don't know because I don't know what you mean by "including variable labels (as an additional column)" which sounds like something very distinctive that you would want to use the skimr api to add.  In other words, you know labels best, you should manage the skim.labelled handling.   

There are thousands of R packages defining different classes.  We have written skimr so that the package authors (who are the ones who really understand the classes) can provide their own skimming infrastructure to support `skim()` just like the  can provide their own `print()` and `summary()` support.

**Comment by rubenarslan** [comment]
Ok, if it's not architecturally impossible that a skimmer for the `labelled` class returns two different types, then I can give it a stab. Sorry this wasn't clear to me. 
Neither [labelled](https://github.com/larmarange/labelled) nor haven are my packages, so not sure I know best.

As to what I meant by including variable labels I meant `attribute(data$variable)$label`. A lot of different packages set these (haven, labelled, Hmisc). I tried making use of these (and other things), [here](https://github.com/rubenarslan/codebook/blob/6fee937feb6f5da35c01e6c7a876fbfad8f4272b/R/codebook.R#L255). I know there are thousands of R packages, but in that ecosystem I don't know when to judge something mainstream enough for inclusion in a package like `skimr`.

**Comment by elinw** [comment]
The columns in the example that you have do not have that classes that they seem to have `class(s1$fac)` is  is "labelled" and the same is true for `class(s1$num)`.  I think it is worth talking to the maintainer of the labellled package about changing that so the classes are actually different or at least storing the underlyng type as an attribute.  

If a lot of packages use these and you come up with a way to make a function that is universal across all of those packages without needing extra code we could look at adding that function to the "stats" set of available functions, and then  maybe users could add if they know the labels are there.  It might be something like "top_counts" since if there are 100s of labels we couldn't put them in a nice looking horizontal table.

**Comment by elinw** [comment]
By the way now that I look at what you are doing, it's a great project.  I think that there's a problem with labelled in that it's not returning the type and you could probably do a lot of what you want with skimr but you might want to break it out into parts. As I said above there's an issue with returning all of the labels if there are a lot of labels, in that case you would want something that gives you a vertical list.  You could use the long skimr_df format but potentially do something else with it rather than use the normal skim printing.

**Comment by rubenarslan** [comment]
Thanks for your advice! I'll look into it, and I also contacted the labelled maintainer about your suggestion.

**Comment by larmarange** [comment]
Thanks for your comment on https://github.com/larmarange/labelled/issues/22

There are several things to consider. First of all, the `labelled` class was not defined by the `labelled` package but by Hadley Wickham in `haven` package.  The purpose of this class is to support labels drom SPSS and STATA. 

The `labelled` package was developed to provide additional functions to mange such class. But technically, the class is directly imported from `haven`. See https://github.com/larmarange/labelled/blob/master/R/labelled.R

Therefore, if additional `labelled_character` and `labelled_numeric` are needed, it should be discussed directly in `haven`. 

Now, regarding the issue you encounter, it's very easy to handle the two types of objects, without additional classes. The function `is.numeric`, `is.character` and `typeof` works perfectly well with `labelled` vectors. You just need to add a test:

```
fun.labelled <- function(x, ...) {
  if (is.character(x))
    fun.labelled_character(x, ...)
  else
    fun.labelled_numeric(x, ...)
}
```

You can see an example with `describe` method in `questionr` package (https://github.com/juba/questionr/blob/master/R/describe.R)

PS: I'm discovering your skimr and codebook projects. Very promising.

Best regards

**Comment by rubenarslan** [comment]
@larmarange yes, you're right, it's easy to fork after. In this specific case, it would have been easier if they were different classes, but maybe it's a very specific case. If I add classes for skimming, summarising, autoplotting, would the labelled package be the right place for a PR? Or haven?

**Comment by larmarange** [comment]
What do you mean by adding classes for skimming, summarising, autoplotting?

If you want to create distinctive labelled_character / labelled_numeric class, it should be discussed in haven.

If you mean adding new methods for labelled class, for example skim.labelled function,  labelled would be more appropriate, or directly in skimr if relevant.

Hope I'm clear.

**Comment by elinw** [comment]
The issue is that if you have say 5000 columns doing the individual tests is going to be painful.  Do you understand how it is that the tibble labels (under the column names) actually know the underlying class?

**Comment by larmarange** [comment]
Regarding a labelled vector, it could be seen as a numeric or a factor, depending to the context.

When you import survey data, you could have a vector with 5 unique values and 5 value labels, corresponding to a categorical variable (and there could be presented as a factor)

On the other hand, you could have an age variable, with just a label on 99 value to say that 99 correspond to missing data, or to "99+". In such case, that vector is much more  an numeric variable.

**Comment by elinw** [comment]
So maybe at least labelled should be treated as factor, it would be a useful improvement on treating them as character.

**Comment by elinw** [comment]
So in V2 you can assign one type the handling of another type so you might be able to do 
```
new_skim <- skim_with(labelled = skimr::get_skimmers.factor())
```

**Comment by elinw** [comment]
This is an old one that I ran into at work this week.  These are really super painful to work with and I was using skimr a lot to help me process because I had to convert some to numerics, some to ordered factors, some to factors etc and also do zap_labels().  So as I was iterating through the data and finding different problems I would have really liked to have them separated since they can be really deceptive.

**Comment by larmarange** [comment]
If I understand properly, the challenge is to define an algorithm to guess (except if expressed by the user) how to handle a labelled vector (as a character, as a numeric vector or as a factor)?

One option would be to consider their type (character / numeric), to present them as a character or a numeric variable and simply to add a columns with a top counts of the defined value labels.

In addition, for `haven_labelled_spss` class, an additional col with the number of user-defined missing could be relevant.

Regards

**Comment by larmarange** [comment]
By the way, should skimmers for haven_labelled class be included in `skimr` or in `labelled` packages?

**Comment by larmarange** [comment]
OK, sorry I have explored a little more the code of your package, and it seems difficult to produce a different output table for vectors of the same class.

Maybe, in that case, the support of labelled vectors could be minimum, with the following results by default:

- type (character or numeric)
- missing
- complete
- n_unique
- n_val_labels (number of defined value labels)
- min and max (NA if character vector)
- top_counts
- hist (if numeric)

It should cover most cases.  For other cases, the user will have to define how they want to handle their labelled vectors, e.g. if they want to consider them, in particular by applying `to_factor` to the data.frame, this function providing several options for mass transformation.

**Comment by elinw** [comment]
I think that’s fine because the idea is that you use it after different steps, for example after you change “dk” to NA where showing the n_value_labels or top_counts would remind you that you need to droplevels() as well as convert to NA.
I don’t think we want to do things line min, max, hist on the variables until they are converted to the core r types.  The way labels are handled for numerics is really awful.

**Comment by elinw** [comment]
So trying
```
set.seed(123)
library(labelled)
 df <- data.frame(x = rep(c("A", "B"), each = 50),
                y = rnorm(100), stringsAsFactors = FALSE)
df$y <- labelled(df$y, label = "Y variable", labels = c())
class(df$y)
"haven_labelled"
typeof(df$y)
[1] "double"
```

What would probably need to happen to stay with the v2 architecture is to make a somewhat complex `skim_by_type.haven_labelled` method that would then use `typeof()` to separate out the actual types that are present and then ... handle the possibility of multiple types.    
Alternatively it could be smart to preprocess to change the classes to e.g. haven_labelled.factor.

**Comment by larmarange** [comment]
"haven_labelled" class has been defined by `haven` package and I do not think that the definition of the class will change again.

The best approach is in fact to use `type_of()`.

Regards

**Comment by michaelquinn32** [comment]
For v2, you should either call `skim_with()` to set the new class ("haven_labelled") or create a new method for `get_skimmers()`. The docs on supporting more classes in V2 is here:
https://github.com/ropensci/skimr/blob/58b9e30baac7b75691d999fb3ea2e3d34a730f43/R/get_skimmers.R#L38

And longer form here:
https://github.com/ropensci/skimr/blob/v2/vignettes/Supporting_additional_objects.Rmd

**Comment by elinw** [comment]
So interestingly, in v2 with all the changes we have made in the last two weeks for `sf` I think that labelled will work really well using that approach.  I would say our model is that the other packages should support their own skimmers ... but I have also considered if we should have skimrExtra for some of these because we can't support everything in skimr itself because it is an endless list.

**Comment by elinw** [comment]
I think in v2 ... 

```
library(skimr)
set.seed(123)
library(labelled)
 df <- data.frame(x = rep(c("A", "B"), each = 50),
                y = rnorm(100), stringsAsFactors = FALSE)
df$y <- labelled(df$y, label = "Y variable", labels = c())

get_skimmers.haven_labelled <- function(column) {
  haven_labelled = sfl(
    skim_type = "haven_labelled",
   type = ~ typeof(.),
   var_label = ~var_label(., unlist = TRUE),
   n_labels = ~ length(val_labels(.))
  )
}

skim(df)

```

works, yielding

```
── Data Summary ────────────────────────
                           Values
Name                       df    
Number of rows             100   
Number of columns          2     
_______________________          
Column type frequency:           
  character                1     
  haven_labelled           1     
________________________         
Group variables            None  

── Variable type: character ─────────────────────────────────────────────────────
  skim_variable n_missing complete_rate   min   max empty n_unique whitespace
1 x                     0             1     1     1     0        2          0

── Variable type: haven_labelled ────────────────────────────────────────────────
  skim_variable n_missing complete_rate type   var_label  n_labels
1 y                     0             1 double Y variable        0

```
