### ISSUE TITLE
skimr::kable() %>% kable_extra

### ISSUE THREAD

**Issue by ssp3nc3r** [ropensci/skimr#328]
I'm trying to resize fonts for a skim table: _e.g._, 

`skimr::skim(mtcars) %>% skimr::kable(format = 'latex', booktabs = T) %>% kable_styling(font_size = 9)
`

Without kable_styling, the above works. Any chance we can make this a feature request? Or some workaround?

**Comment by haozhu233** [comment]
Maybe we should think about a `broom::tidy` like function to export the print results to an object that can be printed by `kable`.

In fact, when I do `skim(mtcars) %>% skimr::kable(format = "latex", booktabs = T)`
I'm getting
```
Skim summary statistics  
 n obs: 32    
 n variables: 11    

Variable type: numeric

| variable | missing | complete | n  |  mean  |   sd   |  p0  |  p25   |  p50  | p75  | p100 | 
...
```
The table above is clearly a markdown table, instead of a LaTeX one.

**Comment by elinw** [comment]
Are you using the released version or the current master? We've done a little work in master so you should not need to use skimr::kable.

I'm going to attach a pdf below but give some background first.

Because we had to write our own implementation of kable to support the very complex print object that skimr produces (which is a series of separate data frames) the print object is not really pipeable. Pipes work with a single data frame.  So what happens is that the long skim object is what is passed on to the next function.   So in my experiment with what you are saying kableExtra is getting the long skim_df not that wide print object.  I think to use kableExtra you would need to do something like `skim_to_wide()` and then filter and select as desired.  Or do `skim_to_list()` and select a single type.

Here's what I see.  First I'm attaching a pdf of some experiments with this.  As you can see the font size does change (I have to say I was somewhat pleasantly surprised to see that kableExtra worked at all!).  

Here's what is in my rmarkdown file. https://gist.github.com/elinw/f4fc1a9c7962cccdce26916474bcd7da.
As you can see I use results = 'asis' in my  chunks and also specify a latex engine in the YAML.  This is documented in the Using Skimr vignette.  

[kableextra.pdf](https://github.com/ropenscilabs/skimr/files/1927602/kableextra.pdf)

Overall we are planning to rethink the whole implementation of printing based on @haozhu233 's earlier suggestion.  We are also looking at whether the skim_df object should potentially be what is now skim_to_wide but that's a major API change.

**Comment by ssp3nc3r** [comment]
Thanks!  I had first used the cran version, and then switched to the GitHub development version when I had trouble. I'll read the above documents and rmd file. Since you point out that it's a "a series of separate data frames", perhaps I can just call each list element separately within kable, something like the example in Xie's _Bookdown_, pp. 30-31,

```
knitr::kable( list(
head(iris[, 1:2], 3),
head(mtcars[, 1:3], 5) ),
  caption = 'A Tale of Two Tables.', booktabs = TRUE
)
```

If I don't see something more direct from the reading you provided, I'll try this.

**Comment by elinw** [comment]
mtcars is kind of a special case since it just has one data type, so skim_to_wide() would actually probably give you what you need.  The issue for us is that some data sets have many types so that means that we have many separate subtables.

**Comment by ssp3nc3r** [comment]
Yes, perhaps that wasn't the best example. Here's my workaround using a combination of `skimr::skim_to_list()` and `knitr::kable()`, which seems to work well for my purposes:

```
library(magrittr); library(kableExtra)

skimr::skim_to_list(iris) %>% .$factor %>% 
  knitr::kable( caption = 'Factor Variables', format = 'latex', booktabs = T ) %>% 
  kable_styling(latex_options = 'HOLD_position', font_size = 9)

skimr::skim_to_list(iris) %>% .$numeric %>% 
  knitr::kable( caption = 'Numeric Variables', format = 'latex', booktabs = T ) %>% 
  kable_styling(latex_options = 'HOLD_position', font_size = 9)
```

**Comment by elinw** [comment]
That's a good approach. There are some other ways but I like that one. I think we should document that example, if you don't mind me using it.

**Comment by pat-s** [comment]
@ssp3nc3r Thanks for sharing this. Helped me splitting factor and numerics and being able to adjust the font size!

**Comment by elinw** [comment]
As soon as we release v2 I'm going to close this issue, v2 is currently in master and if you would want to try it to make sure it addresses your issues that would be great. You might have to read the documentation because we are now using the kable API by default. Some details here: https://ropensci.org/blog/2019/10/29/skimrv2/   @ssp3nc3r  @pat-s @haozhu233 @michaelquinn32
