### ISSUE TITLE
Suggestion: option for display order on grouped data

### ISSUE THREAD

**Issue by jzadra** [ropensci/skimr#339]
I'd like to suggest that an option be made available to arrange the results of `skim()` on grouped datasets by the variable first, then the group.  I often like to compare values between groups, but if I have 6 numeric vars, then I'm trying to compare row 1 to row 7.

**Comment by elinw** [comment]
This is an issue we've discussed before and I believe I provided some code for.    Let me take a look in the closed issues.  We probably should document that.

**Comment by elinw** [comment]
Here is one previous discussion https://github.com/ropenscilabs/skimr/issues/264 . (If that issue is not actually what you mean, please post a comment). 

I really think the key is using skim_to_wide and then using dplyr to arrange the table(s) exactly as you want to print them.  As we move to version 2,  which will use skim_to_wide as the core returned object lots of these nice to have things are going to be a lot simpler to implement.
