### ISSUE TITLE
Integer is not treated as a numeric type 

### ISSUE THREAD

**Issue by benwhalley** [ropensci/skimr#342]
I realise this is an issue caused by R's type system, but I do still find it unintuitive that an integer is not a numeric type and wonder if skimr really needs to distinguish between integer and numeric for the purposes of summaries? e.g. 

```
df <- tibble(a=1:2, b=1.1:2)
myskim1 <- skim_with(numeric = sfl(iqr = IQR), append=F)
myskim2 <- skim_with(integer = sfl(iqr = IQR), numeric= sfl(iqr = IQR), append=F)

myskim1(df)
myskim2(df)
```

Only the second function produces what might be reasonably expected, given that `is.numeric(1)==TRUE`

Can anyone think of a use case where integers should be handled differently to the numeric type? If so, perhaps this could be accommodated by defaulting to setting the integer skim functions to be the same as the numerics, unless someone also passes in a separate `sfl` for integers?

**Comment by elinw** [comment]
The integer functions returned are actually the same by default, but yes, as you said, because of R's typing system they are in separate sub tables.   One thing that you can do if you want them in a single table is to use skim_to_wide and then filter for both integer and numeric, selecting just the statistics that they use.   This is one of the things that I think the roadmap for v2 (which will be built around a skim_to_wide base) will make more intuitive.  
  
In terms of the skimr purpose of giving you a quick overview of what is in a data set you were just given it is useful to know exactly what the type is.  Since another of our key other use cases is that someone has a data set and is iteratively cleaning it, another option is to convert the integers to numerics and rerunning to get the table that you want.   Depending on your data set you may actually want to convert to ordered factor after cleaning (very common in survey data where they have the 5 point scales Strongly Agree ... Strongly Disagree.

**Comment by michaelquinn32** [comment]
Thanks for the questions Ben!

This is a good point, that I'm not sure about how we can address this.

@elinw  brings up a good point, and it was tied to v1. We needed separate treatment for double and integer vectors (the numeric types), due to how we handled dispatch within `skim()`. This isn't true any more, since we're now handling dispatch with S3.

In that case:

```
hello <- function(x) UseMethod("hello")
hello.default <- function(x) print("hello")
hello.numeric <- function(x) print("hello number!")

hello("c")
# [1] "hello"

hello(1L)
# [1] "hello number!"
```

My solution for now is to just rephrase Ben's questions:

1. We currently have the same functions for numeric and integer. Is there an advantage to displaying these separately in the skim() output?
2. We support defining a special integer type separate from numeric in v2. I've confirmed this works in my local branch.
3. Is the current default ultimately more or less helpful than combining all numeric values together?

Any other input here would be great.

Here's an example of what Ben's approach would look like.

```
tibble(1:3) %>% skim()
Skim summary statistics
 n obs: 3 
 n variables: 1 
── Variable type: numeric  ────────────────────────────
# A tibble: 1 x 12
  variable missing complete     n  mean    sd    p0   p25   p50   p75  p100 hist 
* <chr>      <int>    <int> <int> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <chr>
1 1:3            0        3     3    2.    1.    1.  1.50    2.  2.50    3. ▇▁▇▁▇

new_skim <- skim_with(integer = sfl(mad), append = FALSE)
Creating new skimming functions for the following classes: integer.
They did not have recognized defaults. Call get_default_skimmers() for more information.

tibble(1:3) %>% new_skim()
Skim summary statistics
 n obs: 3 
 n variables: 1 
── Variable type: inte──────────────────────────────
# A tibble: 1 x 2
  variable   mad
* <chr>    <dbl>
1 1:3       1.48
```

**Comment by elinw** [comment]
Right so for v2 one question is what is the default for the print.
Also ... are there any formatting issues that are/should be separate for
the two types.
In a lot of the sample data sets you see things that are integers treated
as numeric and I think we handle the decimals correctly in those cases.

Though ... actually we did handle ordered factors and factors in one print
table in v1 and we could look at that.  If v2 gave us the flexibility to
also decide whether to keep them together or separate that would open up
the possibility of doing some separate stats for ordered (like a cumulative
count in addition to top count .... or a kind of histogram) .

**Comment by michaelquinn32** [comment]
Since we currently treat double and integer the same in v2, dropping integer as a default class seems better to me right now. Anyone disagree with that?

**Comment by elinw** [comment]
I just have been working on writing tests in another project and I feel like it is really painful to discover that something is an integer when you are trying to do expect_equal.  So personally I would just as soon keep them separate and have the user make the decision to combine them.  I think it is probably easier to combine than to separate.    On the other hand, if we want to do combining I'd recommend adding a "statistic" that shows the actual class ... that actually might be the best option (kind of like having the is.ordered() function for factors which solves the problem of not realizing that the factor is ordered or that it is not when it should be).

**Comment by elinw** [comment]
Whatever default we pick we need an option to allow the other.  There are some situations where it matters and some where it does not.

**Comment by michaelquinn32** [comment]
Treating integer and numeric as the same will be the default in v2
