### ISSUE TITLE
Print variables in original order

### ISSUE THREAD

**Issue by GegznaV** [ropensci/skimr#350]
In summaries of each type of variables (nulericals, factors, etc.), is there a way to get variables printed in the order as they appeared in the original dataset and not sorted alphabetically? Here is an example of output for numerical variables only:

```r
# Desired not sorted order of variable names
names(iris)
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width" "Species"

# `skim()` sorts variables alphabetically
skimr::skim_with(numeric = list(hist = NULL))
skimr::skim(iris) 
#> / ... the output was truncated manually ... /
#>
#> -- Variable type:numeric ---------------------------------------------
#>      variable missing complete   n mean   sd  p0 p25  p50 p75 p100
#>  Petal.Length       0      150 150 3.76 1.77 1   1.6 4.35 5.1  6.9
#>   Petal.Width       0      150 150 1.2  0.76 0.1 0.3 1.3  1.8  2.5
#>  Sepal.Length       0      150 150 5.84 0.83 4.3 5.1 5.8  6.4  7.9
#>   Sepal.Width       0      150 150 3.06 0.44 2   2.8 3    3.3  4.4
```

Related StackOverflow [issue](https://stackoverflow.com/questions/51383339/).

**Comment by elinw** [comment]
As I pointed out in that question on Stack Overflow the sort is created pretty deep inside the print method, and then  there is not an easy way to do it because you can really work directly on the print object.  That's one reason that skim_to_list() and skim_to_wide() are so important.    
v2 rethinks things by using skim_to_wide() as a basis and therefore I think it makes sense to either offer this as an option or to create our version of arrange() that specifically asks for the original order, which is something a lot of people have asked for.

**Comment by elinw** [comment]
It's because of the way sort works in R combined with spread(), which is either ascending or descending by alphabet. Arrange has the option of using a custom order.   I'm not sure what you are thinking interms of as.factor(), we don't do anything like that, the name variable (along with everything else except for value) is a character variable.    You may be assuming that the skim_object looks like the print version; it does not . It is a long data frame which the print subsets by type and then spreads.

**Comment by GegznaV** [comment]
>  I'm not sure what you are thinking in terms of as.factor(), we don't do anything like that

My idea is in pull request #351: you should create a variable with the correct order of levels otherwise base **R** implicitly orders the levels alphabetically.

**Comment by michaelquinn32** [comment]
v2 always keeps the original variable order, and the wide format of the original data makes it play nicer with functions like `dplyr::arrange()`.
