### ISSUE TITLE
Feature request: confidence intervals for summary statistic

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/skimr#353]
In future releases, will it be possible for `skimr::skim()` to also produce confidence intervals for the mean and median values for numeric variables, in addition to the existing information it outputs?

Thanks.

**Comment by michaelquinn32** [comment]
This seems unlikely to happen by default. Because:

- there's already a large number of summary statistics for numeric variables (close to too many, IMO)
- median CI's are harder to get right in all circumstances, and doing a bootstrap isn't exactly in the `skimr` philosophy (a quick "read" of your data). There's a discussion of approaches here: https://www.afit.edu/stat/statcoe_files/CI_for_Population_Median.pdf

`skimr` is fully customizable, and you're free to add your own statistics. I believe that V2 does a good job of handling this, and I plan to work on working more on the v2 release next week (I've been busy with other stuff recently).

Here's how you would add your own stat in v2:
https://github.com/ropensci/skimr/blob/v2/R/skim_with.R
