### ISSUE TITLE
Consider namespacing statistics

### ISSUE THREAD

**Issue by michaelquinn32** [ropensci/skimr#447]
We reuse statistical functions and the name of columns they generate throughout `skimr`. For example, we have a min for characters (the minimum string length) and a min for dates (the earliest date).

Combining different data types into a single column forces a coercion. As of right now, `dplyr::bind_rows()` won't proceed if this is going to happen, and it's unclear whether it should.

A more sensible approach might be to use the sfl type to provide a column namespace, like `numeric.sd`, `character.min`, etc. This has usability costs, in that subsequent operations over different statistics will need some sort of combination (`numeric.missing > 0 & factor.missing > 0`).

Open questions include:

1. If we go that route, do we strip the namespace from the printed results?
2. Best way to educate users of this change?

**Comment by elinw** [comment]
I definitely think we strip that from the results although now that I wrote that I think it's mainly because it is redundant with the header.  If the skim object was a sparser block diagonal data frame would that potentially impact performance?

**Comment by michaelquinn32** [comment]
We should test on performance. I imagine that there will be a negative impact. There will also be a problem with memory and our commitment to "no surprises."

I really don't like the printed output not matches what users will try to filter on. I think some of this can be simplified by adding another feature to the sfl(). We'll have type skimmers and base skimmers. The latter will be those functions called for all data types in skimr: things like missingness and completeness.

**Comment by elinw** [comment]
I think that's a good point about the people who do post skim processing ... but then again I think that's a different category of users than the ones who are just running and looking at outputs.  Would we have to further extend the dplyr functions to deal with that? 
Also what about the functions that are the same for all classes? Such as complete, missing, n.

**Comment by michaelquinn32** [comment]
>  Also what about the functions that are the same for all classes? Such as complete, missing, n.

That's coming next. I'll be moving those into skim_with, which will have a "base" skim_type. For the user, it shouldn't seem any different from setting the "numeric" or other data types.

I'm also considering changing the base types from complete, missing, n  to n_missing and complete_rate. `n` is given in the skim_summary now. It's less useful to show in every row. complete and missing give similar information, but switching the presentation of the data supports some useful filtering.

```
skim(data) %>%
  dplyr::filter(complete_rate < .95)
```

Or

```
skim(data) %>%
  dplyr::filter(n_missing > 20)
```

**Comment by elinw** [comment]
Yes I think the n thing is redundant if you have missing and complete and people can add it if they want it for a publication table, plus as you said we show it in the summary.

Following on that idea, here's what bothers me about the namespacing into a block diagonal single data frame.  It's just not good practice to have structural blanks. We had them before because we had kind of a block diagonal plus some full columns (the base) but it's much worse now.  If I was building a relational data base I think I would consider making a separate table for each, and in this case that would essentially be creating a list of data frames one for each type (named after the type).  In other words, why shouldn't our default object be a list and then the option be the wide block diagonal data frame (maybe with the base).   
Then we could also get rid of the name spacing which is a bit awkward as we discussed before.

The downside would be that we would have to deal with piping requiring a data frame. That said we already have a function for pulling out a specific type and also since we are already extending the dplyr functions maybe we would modify them again to  (a)  default to the first element of the list, (b) give a warning when there hasn't been the select from the list step, or (c) support passing in a name from a list as the data frame for a dplyr function e.g. `filter(numeric, Sepal.Length > 5)`.

I think I would use data frames rather than tibbles since they are so much more stable and also we don't want that tibble wrapping on the print anyway.
