### ISSUE TITLE
skimr is scheduled for archival on CRAN

### ISSUE THREAD

**Issue by IndrajeetPatil** [ropensci/skimr#455]
@rubenarslan and I received the following message today-
![image](https://user-images.githubusercontent.com/11330453/58380222-a4db0480-7f7c-11e9-9456-661d81677d4e.png)

`skimr` is failing on a single platform in `CRAN`'s daily checks-
![image](https://user-images.githubusercontent.com/11330453/58380293-567a3580-7f7d-11e9-9759-6db6a4245925.png)

Are there plans to submit a newer version before 9th of June? 
If not, our `codebook` and `groupedstats` packages, which depend on `skimr` will also be archived. 

Thanks.

P.S. I haven't blacked out our e-mail addresses in the pic above because they are already in the public domain on CRAN website.

**Comment by hadley** [comment]
The actual problem is here: https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/skimr-00check.html

This is probably the result of the new tests run in Latin1 locale, and depending on how you’re generating the Unicode, probably only requires a small fix (I’d start by looking just at the text). This is something we’ve had to fix in a couple of packages, so please let me know if you get stuck.

**Comment by elinw** [comment]
Thanks all we will fix ASAP

**Comment by elinw** [comment]
New release is on its way to CRAN.
