### ISSUE TITLE
installation conflict with dplyr

### ISSUE THREAD

**Issue by FabianRoger** [ropensci/skimr#549]
I just tried to install `skimr` with `install.packages("skimr")` and I got and `Error in install.packages : Updating loaded packages` error. However `skimr` was not installed on my system. Notably the error was even given after restarting the RSession (multiple times)

When I installed it anyway and the loaded `skimr`, loading `dplyr` second failed with 

    Package ‘dplyr’ version 0.8.0.1 cannot be unloaded:
    Error in unloadNamespace(package) : namespace ‘dplyr’ is imported by ‘skimr’ so cannot be             unloaded

It seems that for 1) `skimr` tries to uptade `rlang` (?) and for 2)  also loads `dplyr`? This seems like a bug?

**Comment by elinw** [comment]
It could be that you can't update your packages because you have already loaded them.  So what you should try is to first update  dplyr and rlang and then update skimr.  But because the tidyverse has a lot of interdependencies you may need to detach (unload) them first.  Skimr definitely has minimum versions for those packages because it's basically impossible to support both the older and newer versions.

Let me know what happens when you try this.

**Comment by michaelquinn32** [comment]
It also sounds to me like you're using the RStudio option to reload data from previous sessions on startup. Jenny Bryan discusses why setting `'R --no-save --no-restore-data` is much better:
https://www.tidyverse.org/blog/2017/12/workflow-vs-script/

Here is a fix from within RStudio:
https://community.rstudio.com/t/how-to-clear-the-r-environment/14303/6

**Comment by elinw** [comment]
@FabianRoger could you let us know if this was resolved?

**Comment by elinw** [comment]
Closing because of no response, happy to reopen if there is more information.
